### ISSUE TITLE
Data Visualization Via Matplotlib and Seaborn

### ISSUE THREAD

**Issue by Innovator07** [viditvarshney/Tower-Of-Hanoi-Solutions#25]
I would like to contribute on data visualization by using python packages and libraries, this issue is going to help everyone on plotting histograms, bar graphs, and pie chart. basically my issue will be going to help everyone by clarifying there data in efficient and better way and I am using few famous inbuilt packages in my problem: "Matplotlib, Seaborn, pandas". 

[https://colab.research.google.com/drive/1VHf47pFGBN6L7_rrOpK_VZCMOHWF_nQb?usp=sharing](url)

([Training_Images_Data.xlsx](https://github.com/viditvarshney/TOH_HacktoberFest2020/files/5317185/Training_Images_Data.xlsx))

[https://drive.google.com/file/d/1B3HophT_vUFcjAsbCPTCC2X1sedA1_P_/view?usp=sharing](url)

**Comment by viditvarshney** [comment]
Ok, Nice you can do it 

So make a new folder, then inside that folder make a folder with your name 

your files much be elaborative and easy to understand

**Comment by viditvarshney** [comment]
accepted
